### ISSUE TITLE
As a public transport user, I would like to see the new realtimebus implementation (back-end + front-end) with just the realtime-positions of the buses.

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/realtimebus#51]
- [x] webcomp-smartmobility @Piiit Done as of version 1.1.0
- [x] back-end @bertolla https://github.com/noi-techpark/realtimebus-v2/pull/16

**Comment by rcavaliere** [comment]
This user story just relates to the integration of this PR: https://github.com/noi-techpark/realtimebus-v2/pull/16
Please upgrade the current implementation (back-end + front-end -> web-component) so that we can see at least the real-time positions of the SASA buses

**Comment by Piiit** [comment]
@rcavaliere OK, but I will move it back to todo

**Comment by Piiit** [comment]
@rcavaliere Please always add new stuff to (best) backlog and if urgent to todo, because testing comes after integration... and it is difficult for me to understand whether it is all done already I just need to test it, or if I need to still integrate it. Thx :-)

**Comment by rcavaliere** [comment]
@Piiit that's fine. I was not sure that such contributions came during this sprint, but let's do like you suggested.

**Comment by Piiit** [comment]
@rcavaliere Sure, adding new tasks during the sprint is ok, if not otherwise possible. Just add it to TODO then, and move it to the top if it is really urgent...

**Comment by bertolla** [comment]
Deployed the new version of the backend. Is there anything left to do?

**Comment by Piiit** [comment]
What is the current endpoint? I cannot see any data on https://webcomponents.opendatahub.testingmachine.eu/webcomponent/7620f04d-ed08-4770-bbda-dfe959ae078e

**Comment by rcavaliere** [comment]
@Piiit the end point should be this one
@bertolla did you consider all the instructions of Daniel (see mail 16.6 at 18:39): I put it there:

"Ho appena caricato le modifiche da te richieste, quindi applicando i PR [1] e [2]:

    Il server non genera più una posizione approssimata attraverso una procedura di interpolazione
    il server riesce ad importare il dataset attuale (c’era un problema con il dataset VDV attuale)
    il client mostra solo i veicoli (senza fermate e linee)
    il client permette di filtrare per città o linea


In aggiunta, ho anche abilitato un endpoint “websocket” [3] che permette di fare un “broadcast" in tempo reale a tutti i “subscriber” connessi ad ogni aggiornamento da parte di SASA. Questo rende più reattiva la mappa rispetto al sistema di caricamento precedente (che comunque è ancora presente nel caso il browser non sia compatibile con questa tecnologia).

@PatrickB: Non c’è più bisogno di indicare i dataset dei percorsi (CSV+KML) durante l'import, quindi per importare i dati attuali va utilizzato il “vecchio” endpoint [4]."

[1] https://github.com/noi-techpark/realtimebus-v2/pull/16
[2] https://github.com/noi-techpark/webcomp-smartmobility/pull/5
[3] “/geojson/realtime/stream"
[4] “/vdv/import"

Please do a check if everything is configured well, otherwise I ask Daniel for clarifications

**Comment by rcavaliere** [comment]
@bertolla let's put this user story in stand-by, this PR was not was I expected. Next steps:
- [ ] @rcavaliere will provide more detailed inputs to Daniel R. for the expected implementation
- [ ] Daniel R. will prepare a new PR for the new system
- [ ] @bertolla will integrate the PR in our testing environment

**Comment by rcavaliere** [comment]
Next steps defined today:
- [ ] @bertolla makes a logging of the real-time data and shares the logs with @rcavaliere 
- [ ] @rcavaliere makes an analysis of the raw real-time data stream

**Comment by bertolla** [comment]
@rcavaliere 
Is it still necessary or is the data provided by Daniel good enough?

**Comment by rcavaliere** [comment]
No more necessary
