### ISSUE TITLE
As a PM I would like to deepen the real-time data flow coming from SASA (real-time bus positions)

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/realtimebus#52]

**Comment by rcavaliere** [comment]
Analysis completed. 
I have drafted a document explaining in detail the real-time SASA dataset (see attachment)
[200904_SASA_RealTimeData_EndPointDocumentation.pdf](https://github.com/noi-techpark/realtimebus/files/5174852/200904_SASA_RealTimeData_EndPointDocumentation.pdf)
The dataset just provides the current positions of the buses, together with some attributes that allow to understand who it is (line, departure time, etc.).
A combination between this dataset and all rest of public transportation data (see https://suedtirolmobil.info/de/) is definitely possible and can provide an added value to end-users. A mix with what is visible on mobility.meran.eu can be obtained
E.g. when the line details are shown on the map it could be also possible to show, if available, the real-time position of the vehicle. This is possible by setting the line ID and the planned departure time of the journey.

My suggestion for the next steps:
- [ ] define agreement with STA and SASA to integrate the correspondent datasets in the ODH
- [ ] complete user story https://github.com/noi-techpark/issues/issues/29 to check if it's easy to use to integrate stuff in   https://suedtirolmobil.info/de/ for prototypes implementation
- [ ] involve local IT companies in the development of such prototypes implementation, e.g. for the a new implementation of mobility.meran.eu

@ohnewein what do you suggest

**Comment by sseppi** [comment]
@rcavaliere is it really done? The next steps are all still open.

**Comment by rcavaliere** [comment]
The deepening work is done, which is the content of this user story. Other activities should be part of additional user stories
